acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('chpass/', views.chpass, name="chpass")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('update/<bpk>', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('trans/', include("trans.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name="vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create/', views.create, name="create"),
    path('delete/<tpk>', views.delete, name="delete"),
    path('update/<tpk>', views.update, name="update"),
    path('chodelete/<cpk>/<tpk>', views.delete_choice, name="chodelete")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.top}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.contrib import messages

# Create your views here.
def index(request):
    t = Topic.objects.all()

    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(request, "vote/detail.html", context)

def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    messages.info(request, "투표가 이루어졌습니다")
    return redirect("vote:detail", tpk)

def cancel(request, tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(u)
    u.choice_set.get(top=t).choicer.remove(u)
    messages.info(request, "투표를 무르셨습니다")
    return redirect("vote:detail", tpk)

def create(request):
    if request.user.is_anonymous:
        messages.error(request, "비정상적인 접근입니다")
        return redirect("acc:login")

    if request.method == "POST":
        s = request.POST.get("sub")
        user = request.user
        c = request.POST.get("con")
        ch = request.POST.getlist("cho")
        cm = request.POST.getlist("com")
        t = Topic(subject = s, maker = user, content = c)
        t.save()
        for name, com in zip(ch, cm):
            Choice(top=t, name=name, comment=com).save()
        messages.success(request, "해당 주제의 투표가 생성되었습니다")
        return redirect('vote:index')
    return render(request, "vote/create.html")

def update(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user == t.maker:
        messages.error(request, "비정상적인 접근입니다")
        return redirect('vote:index')

    cset = Choice.objects.filter(top=t)
    cs = t.choice_set.all
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        ch = request.POST.getlist("cho")
        cm = request.POST.getlist("com")
        nch = request.POST.getlist("ncho")
        ncm = request.POST.getlist("ncom")
        t.subject, t.content = s, c
        t.save()

        for i, name, com in zip(cset, ch, cm):
            i.name, i.comment = name, com
            i.save()

        for na, co in zip(nch, ncm):
            Choice(top=t, name=na, comment=co).save()
            
        messages.success(request, "해당 주제의 투표가 수정되었습니다")
        return redirect('vote:index')

    context = {
        "t" : t,
        "cset" : cs
    }
    return render(request, "vote/update.html", context)

def delete(request, tpk):
    t = Topic.objects.get(id=tpk)
    if request.user == t.maker:
        t.delete()
        messages.info(request, "해당 주제의 투표가 삭제되었습니다")
    else:
        messages.error(request, "비정상적인 접근입니다")
    return redirect("vote:index")

def delete_choice(request, cpk, tpk):
    c = Choice.objects.get(id=cpk)
    if request.user == c.top.maker:
        c.delete()
        messages.info(request, "해당 보기가 삭제되었습니다")
    else:
        messages.error(request, "비정상적인 접근입니다")
    return redirect("vote:update", tpk)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>토픽생성</b></h1>

    <form method="POST">
        {% csrf_token %}
        <input type="text" placeholder="INPUT SUBJECT" name="sub" class="form-control mt-5">
        <input type="text" value="{{user}}" disabled class="form-control mt-3 mb-3">
        <textarea class="form-control" style="height: 200px;" name="con" placeholder="INPUT CONTENT"></textarea>
    
        <div class="text-end mt-4">
            <button type="button" onclick="makecho()" class="btn btn-secondary btn-lg">보기생성</button>
            <button class="btn btn-dark btn-lg">토픽생성</button>
        </div>
    
        <div id="here" class="row mt-5"></div>
    </form>
    


    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-sm-4");
            n.innerHTML = "<input type='text' placeholder='INPUT NAME' name='cho' class='form-control'>\
            <textarea class='form-control mt-3 mb-5' name='com' placeholder='INPUT COMMENT'></textarea>";
            d.appendChild(n);
        }
    </script>


{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block con %}
<div class="container mt-5 mt-5">
    <h1><b>{{ t.subject }}</b></h1>

    <div class="text-end">
        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#post">
            ✨
        </button>
    </div>

    <div class="row mt-5">
        <div class="col-sm-8">
            <textarea class="form-control" disabled style="height: 250px;">{{ t.content }}</textarea>
        </div>
        <div class="col-sm-4">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>made by <b>{{ t.maker }}</b></h4>
            </div>
        </div>
    </div>

    <hr>

    {% if user in t.voter.all %}
        <form method="POST" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-sm-4 mb-4">
                        <input type="radio" name="cho" value="{{ i.id }}" {% if forloop.first %} checked {% endif %} class="form-check-input">
                        <label class="form-check-label">
                            <h4><b>{{ i.name }}</b></h4>
                        </label>
                        <div class="progress mt-3 mb-3" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%;">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%</div>
                        </div>
                        <textarea class="form-control mt-3" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4">
                <a href="{% url 'vote:cancel' t.id %}" class="btn btn-danger btn-lg">무르기</a>
                <a href="{% url 'vote:index' %}" class="btn btn-dark btn-lg">뒤로가기</a>
            </div>
        </form>
    {% else %}
        <form method="POST" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-sm-4 mb-4">
                        <input type="radio" name="cho" value="{{ i.id }}" {% if forloop.first %} checked {% endif %} class="form-check-input">
                        <label class="form-check-label">
                            <h4><b>{{ i.name }}</b></h4>
                        </label>
                        <textarea class="form-control mt-3" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4">
                <button class="btn btn-dark btn-lg">투표하기</button>
                <a href="{% url 'vote:index' %}" class="btn btn-dark btn-lg">뒤로가기</a>
            </div>
        </form>
    {% endif %}
</div>

<!-- post Modal -->
<form method="POST" action="{% url 'book:create' %}">
    {% csrf_token %}
    <div class="modal fade" id="post" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">즐겨찾기 추가 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div class="text-end">
                        <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                        <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                    </div>
                    <textarea class="form-control mt-3" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                    <input type="hidden" name="sname" value="[BOARD] {{ t.subject }}">
                    <input type="hidden" name="surl" value="{{ request.path }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창 닫기</button>
                    <button class="btn btn-warning">즐겨찾기 추가</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}

{% block con %}
<h1><b>투표소</b></h1>

<div class="text-end">
    <a href="{% url 'vote:create' %}" class="btn btn-dark">토픽생성</a>
</div>

<div class="row">
    {% for i in tset %}
        <div class="col-sm-4 mt-4">
            <div class="card">
                <img src="{{ i.maker.getpic }}" width="100%" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><b><mark>{{ i.subject }}</mark></b></h5>
                    <p class="card-text">{{ i.content|truncatewords:8 }}</p>
                    {% if user in i.voter.all %}
                        <div class="text-center">
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-outline-dark">결과보기</a>
                        {% if i.maker == user %}
                            <a href="{% url 'vote:update' i.id %}" class="btn btn-outline-primary">수정</a>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#e{{ forloop.counter }}">
                                삭제
                            </button>
                        {% endif %}
                        </div>
                    {% else %}
                        <div class="text-center">
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-outline-dark">투표하기</a>
                            {% if i.maker == user %}
                                <a href="{% url 'vote:update' i.id %}" class="btn btn-outline-primary">수정</a>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#e{{ forloop.counter }}">
                                    삭제
                                </button>
                            {% endif %}
                        </div>
                    {% endif %}
                    <div class="mt-4">
                        투표 참가자 : 
                        {% for i in i.voter.all %}
                            <b>{{ i }}</b>
                        {% endfor %}
                        (총 {{ i.voter.count }}명)
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% for i in tset %}
    <!-- Modal -->
    {% if user == i.maker %}
        <div class="modal fade" id="e{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel"><b>{{ i.subject }}</b> 토픽 삭제 알림창</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <mark><b>{{ i.voter.count }}</b></mark>명이 참여한 투표입니다. 그래도 삭제하시겠습니까?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <a href="{% url 'vote:delete' i.id %}" type="button" class="btn btn-danger">삭제</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

{% endblock %}

templates/vote/update.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>토픽수정</b></h1>

    <form method="POST">
        {% csrf_token %}
        <input type="text" value="{{ t.subject }}" name="sub" class="form-control mt-5">
        <input type="text" value="{{user}}" disabled class="form-control mt-3 mb-3">
        <textarea class="form-control" style="height: 200px;" name="con">{{ t.content }}</textarea>
    
        <div class="text-end mt-4">
            <button type="button" onclick="makecho()" class="btn btn-secondary btn-lg">보기생성</button>
            <button class="btn btn-dark btn-lg">토픽수정</button>
        </div>
    
        <div id="here" class="row mt-5">
            {% for i in cset %}
                <div class="col-sm-4 mb-5">
                    <input type='text' value="{{ i.name }}" name='cho' class='form-control'>
                    <textarea class='form-control mt-3 mb-2' name='com'>{{ i.comment }}</textarea>
                    <div class="text-end">
                        <a href="{% url 'vote:chodelete' i.id t.id %}" class="btn btn-outline-danger">보기삭제</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </form>
    
    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-sm-4");
            n.innerHTML = "<input type='text' placeholder='INPUT NAME' name='ncho' class='form-control'>\
            <textarea class='form-control mt-3 mb-5' name='ncom' placeholder='INPUT COMMENT'></textarea>";
            d.appendChild(n);
        }
    </script>


{% endblock %}