acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('chpass/', views.chpass, name="chpass")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('update/<bpk>', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('trans/', include("trans.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site_name = models.CharField(max_length=100)
    site_url = models.TextField()
    site_con = models.TextField()
    impo = models.BooleanField(default=False)

    def __str__(self):
        return self.site_name

book/views.py
from django.shortcuts import render, redirect
from .models import Book
from django.contrib import messages
# Create your views here.
def index(request):
    if request.user.is_anonymous:
        messages.error(request, "비정상적인 접근입니다")
        return redirect('acc:index')

    b = request.user.book_set.all()
    context = {
        "bset" : b
    }
    return render(request, "book/index.html", context)

def create(request):
    if request.user.is_anonymous:
        messages.error(request, "비정상적인 접근입니다")
        return redirect('acc:index')

    if request.method == 'POST':
        im = bool(request.POST.get("impo"))
        sn = request.POST.get("sname")
        su = request.POST.get("surl")
        sc = request.POST.get("scon")
        Book(user=request.user, site_name=sn, site_url=su, site_con=sc, impo=im).save()
        messages.info(request, "북마크가 생성되었습니다")
        return redirect('book:index')
    return render(request, "book/create.html")

def delete(request, bpk):
    if request.user.is_anonymous:
        messages.error(request, "비정상적인 접근입니다")
        return redirect('acc:index')

    b = Book.objects.get(id=bpk)
    if b.user == request.user:
        b.delete()
        messages.success(request, "북마크가 성공적으로 삭제되었습니다")
    else:
        messages.error(request, "비정상적인 접근입니다")
    return redirect('book:index')

def update(request, bpk):
    if request.user.is_anonymous:
        messages.error(request, "비정상적인 접근입니다")
        return redirect('acc:index')

    b = Book.objects.get(id=bpk)
    if request.method == 'POST':
        im = bool(request.POST.get("impo"))
        sn = request.POST.get("sname")
        su = request.POST.get("surl")
        sc = request.POST.get("scon")
        b.impo, b.site_name, b.site_url, b.site_con = im, sn, su, sc
        b.save()
        messages.info(request, "북마크가 수정되었습니다")
        return redirect('book:index')

    context = {
        "b" : b
    }
    return render(request, "book/update.html", context)

templates/book/create.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>북마크 생성</b></h1>

    <form method="POST">
        {% csrf_token %}
        <div class="text-end">
            <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
        </div>
        <input type="text" name="sname" placeholder="사이트 이름을 입력하세요" class="form-control mt-3">
        <input type="text" name="surl" placeholder="사이트 URL 을 입력하세요" class="form-control mt-4 mb-4">
        <textarea class="form-control" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
    
        <div class="text-end mt-5">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>

{% endblock %}

templates/book/index.html
{% extends 'base.html' %}

{% block con %}
<h1><b>BOOK PAGE</b></h1>

<div class="text-end">
    <a href="{% url 'book:create' %}" class="btn btn-success"> + BOOKMARK </a>
</div>

<div class="row">
    {% for i in bset %}
        <div class="col-sm-4 mb-3 mb-sm-0 mt-4">
            <div class="card" {% if i.impo %} style="background-color: antiquewhite;" {% endif %}>
                <div class="card-body">
                    <h5 class="card-title"><b>{{ i.site_name }}</b></h5>
                    <p class="card-text">{{ i.site_con|truncatechars:20 }}</p>
                    <a href="{{ i.site_url }}" class="btn btn-outline-primary">사이트 이동</a>
                    <a href="{% url 'book:update' i.id %}" class="btn btn-outline-secondary">수정</a>
                    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#e{{ forloop.counter }}">
                        삭제
                    </button>
                </div>
            </div>
        </div>
    {% empty %}

    {% endfor %}
</div>

{% for i in bset %}
    <!-- 삭제모달창 -->
    <div class="modal fade" id="e{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">북마크 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'book:delete' i.id %}" class="btn btn-danger">북마크 삭제</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

templates/book/update.html
{% extends 'base.html' %}
{% block con %}
<h1><b>북마크 수정</b></h1>

    <form method="POST">
        {% csrf_token %}
        <div class="text-end">
            <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off" {% if b.impo %} checked {% endif %}>
            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
        </div>
        <input type="text" name="sname" value="{{ b.site_name }}" class="form-control mt-3">
        <input type="text" name="surl" value="{{ b.site_url }}" class="form-control mt-4 mb-4">
        <textarea class="form-control" name="scon" style="height: 100px;">{{ b.site_con }}</textarea>
    
        <div class="text-end mt-5">
            <button class="btn btn-dark">수정</button>
            <a href="{% url 'book:index' %}" class="btn btn-secondary">뒤로가기</a>
        </div>
    </form>
{% endblock %}